# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudelf < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.27"

  on_macos do
    url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.27/cloudelf_Darwin_x86_64.tar.gz"
    sha256 "7091f746343ab3a42ad1dc73dbdabe740a69305a4444ab640f8851f40868a321"

    def install
      bin.install "cloudelf"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudelf
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.27/cloudelf_Linux_x86_64.tar.gz"
      sha256 "0d6b61a76b3a5f396915045b5bae78699e63dd4885fc4da875aa969ab0047813"

      def install
        bin.install "cloudelf"
      end
    end
  end
end
