# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abovehave < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/abovehave"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/abovehave/releases/download/v0.0.1/abovehave_Darwin_x86_64.tar.gz"
    sha256 "a107445655c6a8478b0e0658391d1c15346895832af75d152085168ad895dc02"

    def install
      bin.install "abovehave"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abovehave
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/abovehave/releases/download/v0.0.1/abovehave_Linux_x86_64.tar.gz"
        sha256 "0fc5eb76c396b47ab2685229b1fbccf67c76162182571927acff4c8a09f9c3e2"

        def install
          bin.install "abovehave"
        end
      end
    end
  end
end
