# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abovehave < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/abovehave"
  version "0.0.5"

  on_macos do
    url "https://github.com/gkwa/abovehave/releases/download/v0.0.5/abovehave_Darwin_x86_64.tar.gz"
    sha256 "30b0e616ca6e5976df0487565ae8127b28e1ba458d06eed90ce76e9e91969335"

    def install
      bin.install "abovehave"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abovehave
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/abovehave/releases/download/v0.0.5/abovehave_Linux_x86_64.tar.gz"
        sha256 "0ce240b3827adc96004fa6bdb4a4080f0c8b8cabee0b78e91892335fe66c5174"

        def install
          bin.install "abovehave"
        end
      end
    end
  end
end
