# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abovehave < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/abovehave"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/abovehave/releases/download/v0.0.2/abovehave_Darwin_x86_64.tar.gz"
    sha256 "c6330181de9b57b251414cbdc374bdb47da20703f9de2279a262db0f22b9ed4b"

    def install
      bin.install "abovehave"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abovehave
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/abovehave/releases/download/v0.0.2/abovehave_Linux_x86_64.tar.gz"
        sha256 "6596e5c4364364e1a197583853ad5513e58a601008cad4d37c4a35661d385ddb"

        def install
          bin.install "abovehave"
        end
      end
    end
  end
end
