# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abroadturn < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/abroadturn"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/abroadturn/releases/download/v0.0.1/abroadturn_Darwin_x86_64.tar.gz"
    sha256 "b8e06d96b7f70d8bed151be85d6eb5f33737f9738fe2ae6dc879af6162246009"

    def install
      bin.install "abroadturn"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abroadturn
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/abroadturn/releases/download/v0.0.1/abroadturn_Linux_x86_64.tar.gz"
      sha256 "d162ffed2f3dcb941ac9c9cf8a22b775f707886f31b6c7262b810edd4fa4d2f5"

      def install
        bin.install "abroadturn"
      end
    end
  end
end
