# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abroadjump < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/abroadjump"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/abroadjump/releases/download/v0.0.1/abroadjump_Darwin_x86_64.tar.gz"
    sha256 "c4acbd3f4256cb3507b3b8f5719002ad8606df5db724c813f4aaa55481fcb575"

    def install
      bin.install "abroadjump"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abroadjump
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/abroadjump/releases/download/v0.0.1/abroadjump_Linux_x86_64.tar.gz"
        sha256 "3d095afde3db4556b013fb45b3802baed8756de6b1f665269c18d9aaeccc8357"

        def install
          bin.install "abroadjump"
        end
      end
    end
  end
end
