# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Abundantvan < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/abundantvan/releases/download/v0.0.1/abundantvan_Darwin_x86_64.tar.gz"
    sha256 "9566aedc87d1477a09e9d0cda4479069d05f82d9a1e612b37ed4864a8d1ff76a"

    def install
      bin.install "abundantvan"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Abundantvan
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/abundantvan/releases/download/v0.0.1/abundantvan_Linux_x86_64.tar.gz"
      sha256 "b575fb926842c0e17894b7b8db3535f650a605bb940931dfa82f72682999c596"

      def install
        bin.install "abundantvan"
      end
    end
  end
end
