# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accidentallysit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/accidentallysit"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/accidentallysit/releases/download/v0.0.2/accidentallysit_Darwin_x86_64.tar.gz"
    sha256 "ee06d4ac0e3317f8e95537ce95eceba59da6a9a4e0031d0fcd94a0db7cd0036f"

    def install
      bin.install "accidentallysit"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Accidentallysit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/accidentallysit/releases/download/v0.0.2/accidentallysit_Linux_x86_64.tar.gz"
        sha256 "c13c6daf430421af61229530d537017125253f8c3549980a971e35bd69081984"

        def install
          bin.install "accidentallysit"
        end
      end
    end
  end
end
