# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accidentallysit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/accidentallysit"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/accidentallysit/releases/download/v0.0.1/accidentallysit_Darwin_x86_64.tar.gz"
    sha256 "14396ed399cdfe129b07b1c2ae1160a0904c15066de02974c7a54e443a15d824"

    def install
      bin.install "accidentallysit"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Accidentallysit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/accidentallysit/releases/download/v0.0.1/accidentallysit_Linux_x86_64.tar.gz"
      sha256 "f9ce6b6d80d9d9755b55260d0e963c7d0eafb2a391be8f84778f2f6a2b601f10"

      def install
        bin.install "accidentallysit"
      end
    end
  end
end
