# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allbranding < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/allbranding/releases/download/v0.0.2/allbranding_Darwin_x86_64.tar.gz"
    sha256 "386784a2886c9a6ce16ec63fc0e87c639c19f49d5948762d833cf167a85c5cdb"

    def install
      bin.install "allbranding"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allbranding
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/allbranding/releases/download/v0.0.2/allbranding_Linux_x86_64.tar.gz"
      sha256 "2babd335ad67e69d212da5edaf335436126a31ccfba45ffa53c1657418015b38"

      def install
        bin.install "allbranding"
      end
    end
  end
end
