# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allgeorgia < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allgeorgia"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/allgeorgia/releases/download/v0.0.1/allgeorgia_Darwin_x86_64.tar.gz"
    sha256 "de9844a85db6ddec83f340ccc185459503ffccf2ee5af58ef2c313ee0a6daa43"

    def install
      bin.install "allgeorgia"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allgeorgia
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allgeorgia/releases/download/v0.0.1/allgeorgia_Linux_x86_64.tar.gz"
        sha256 "42a295045a4908970702be4f9bb10f8518aa1e60e7331acc895d737461e96127"

        def install
          bin.install "allgeorgia"
        end
      end
    end
  end
end
