# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alljuly < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/alljuly"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/alljuly/releases/download/v0.0.2/alljuly_Darwin_x86_64.tar.gz"
    sha256 "d0fa003824e398ae41ae92176edaa2b434a040a775425f101f94b152b70b2bbd"

    def install
      bin.install "alljuly"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Alljuly
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/alljuly/releases/download/v0.0.2/alljuly_Linux_x86_64.tar.gz"
        sha256 "3fb895cde57597a13c9af8594ac3498bc62abb4d34fb5b6546f76233195f399f"

        def install
          bin.install "alljuly"
        end
      end
    end
  end
end
