# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alljuly < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/alljuly"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/alljuly/releases/download/v0.0.1/alljuly_Darwin_x86_64.tar.gz"
    sha256 "50b9d82e42e3434e5995aa089a6cc4cbcd8ae16e5672194d5ff89d319bdd98eb"

    def install
      bin.install "alljuly"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Alljuly
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/alljuly/releases/download/v0.0.1/alljuly_Linux_x86_64.tar.gz"
        sha256 "73117e1b0669708ac921fc5b0d8612fecec1a76c0bf0411eaf5beab7af3345ad"

        def install
          bin.install "alljuly"
        end
      end
    end
  end
end
