# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allparadigm < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allparadigm"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/allparadigm/releases/download/v0.0.6/allparadigm_Darwin_x86_64.tar.gz"
    sha256 "f943b6a6d9efb79b71de46d5f615968373833b88868707befd38109d0c53e98d"

    def install
      bin.install "allparadigm"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allparadigm
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allparadigm/releases/download/v0.0.6/allparadigm_Linux_x86_64.tar.gz"
        sha256 "df3725a29f9d8d3d7ee8b333e3e37583b84a961ec10695e4bf8311d87fb843eb"

        def install
          bin.install "allparadigm"
        end
      end
    end
  end
end
