# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allrabbit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allrabbit"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/allrabbit/releases/download/v0.0.3/allrabbit_Darwin_x86_64.tar.gz"
    sha256 "366d5cb3fb75548d003754fa5fced8efa5155f0e128062853a403378ecb02037"

    def install
      bin.install "allrabbit"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allrabbit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allrabbit/releases/download/v0.0.3/allrabbit_Linux_x86_64.tar.gz"
        sha256 "2972174e82f7154b558a582a8d763cd863f89220454857d6f313941843f47301"

        def install
          bin.install "allrabbit"
        end
      end
    end
  end
end
