# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allrabbit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allrabbit"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/allrabbit/releases/download/v0.0.1/allrabbit_Darwin_x86_64.tar.gz"
    sha256 "5b258a4608dca7360de818c723c9f828132acd10cc297a24f51c3e52bc78cddd"

    def install
      bin.install "allrabbit"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allrabbit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allrabbit/releases/download/v0.0.1/allrabbit_Linux_x86_64.tar.gz"
        sha256 "b7a6ad11f8897617673edfff7b98eae286b80f79ab48bb2f2c33107e60790b2e"

        def install
          bin.install "allrabbit"
        end
      end
    end
  end
end
