# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allrabbit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allrabbit"
  version "0.0.4"

  on_macos do
    url "https://github.com/gkwa/allrabbit/releases/download/v0.0.4/allrabbit_Darwin_x86_64.tar.gz"
    sha256 "8321d31aad132be2ee14657d9926a54d4d571d5e7b7fb6d286543029ba2a9d93"

    def install
      bin.install "allrabbit"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allrabbit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allrabbit/releases/download/v0.0.4/allrabbit_Linux_x86_64.tar.gz"
        sha256 "8714a70f20d98414d2ee9e4757a3e54eacfe2d52217a24a3315880e5adda134b"

        def install
          bin.install "allrabbit"
        end
      end
    end
  end
end
