# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Allsouth < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/allsouth"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/allsouth/releases/download/v0.0.8/allsouth_Darwin_x86_64.tar.gz"
    sha256 "a3b7140dd130868f9df567f317a5aaa89dac298868f74ed6b862bb31523df115"

    def install
      bin.install "allsouth"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Allsouth
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/allsouth/releases/download/v0.0.8/allsouth_Linux_x86_64.tar.gz"
        sha256 "5d9b753e2e8b3322820ee9706e5a5508efd8f18a6106dc7863fec3309b8f8961"

        def install
          bin.install "allsouth"
        end
      end
    end
  end
end
