# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Alwayswin < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/alwayswin/releases/download/v0.0.2/alwayswin_Darwin_x86_64.tar.gz"
    sha256 "813be520df411785b9ac9ed7523c7af7c7eca3fba5457a3e54f5e8c79b49ea5c"

    def install
      bin.install "alwayswin"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Alwayswin
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/alwayswin/releases/download/v0.0.2/alwayswin_Linux_x86_64.tar.gz"
      sha256 "2c7c2a6073ab847e9d4801d808faf85109058d072c31bbf2cc5beacb28f03e81"

      def install
        bin.install "alwayswin"
      end
    end
  end
end
