# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Americanford < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/americanford"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/americanford/releases/download/v0.0.1/americanford_Darwin_x86_64.tar.gz"
    sha256 "595f1a71156ae87c11807c7953b99dbd8a9c06c2900660e93a30b4090f7de2ba"

    def install
      bin.install "americanford"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Americanford
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/americanford/releases/download/v0.0.1/americanford_Linux_x86_64.tar.gz"
      sha256 "5e9573b073a8d52eb54bbc60e857ceadc461e3850e79cd9581abdee5eecfdf83"

      def install
        bin.install "americanford"
      end
    end
  end
end
