# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annuallycould < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/annuallycould"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/annuallycould/releases/download/v0.0.1/annuallycould_Darwin_x86_64.tar.gz"
    sha256 "237fa99de1dbf4cf4e06348480b734c30d614da372241fa5b3c351de3858a8d0"

    def install
      bin.install "annuallycould"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Annuallycould
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/annuallycould/releases/download/v0.0.1/annuallycould_Linux_x86_64.tar.gz"
        sha256 "25478b0cd1cecc8ce69f7ec943db89805a7de3f9a6895f1bd1bb457c817656f7"

        def install
          bin.install "annuallycould"
        end
      end
    end
  end
end
