# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annuallyis < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/annuallyis"
  version "0.0.4"

  on_macos do
    url "https://github.com/gkwa/annuallyis/releases/download/v0.0.4/annuallyis_Darwin_x86_64.tar.gz"
    sha256 "9833bc6c543d03d703b68d2acd4206fb4ae2040bcc277877d68eac496159b673"

    def install
      bin.install "annuallyis"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Annuallyis
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/annuallyis/releases/download/v0.0.4/annuallyis_Linux_x86_64.tar.gz"
        sha256 "7879d823945df8571735a0951a336073ec74442871bf11b08c5c70f411dc8d62"

        def install
          bin.install "annuallyis"
        end
      end
    end
  end
end
