# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annuallyis < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/annuallyis"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/annuallyis/releases/download/v0.0.1/annuallyis_Darwin_x86_64.tar.gz"
    sha256 "0cb2b17d432a86b125dfc94aca8e22a16cbe2a5116186a60bf039d23d0c16517"

    def install
      bin.install "annuallyis"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Annuallyis
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/annuallyis/releases/download/v0.0.1/annuallyis_Linux_x86_64.tar.gz"
        sha256 "cf55133c951989e7c66b1acaf3e6346f6309036c435379c073bc797fe0a989d7"

        def install
          bin.install "annuallyis"
        end
      end
    end
  end
end
