# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annuallydo < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/annuallydo/releases/download/v0.0.1/annuallydo_Darwin_x86_64.tar.gz"
    sha256 "7890a44b94848a785b6c446ac74ea9ecbe18fe364a12035737a2e2b8174893e8"

    def install
      bin.install "annuallydo"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Annuallydo
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/annuallydo/releases/download/v0.0.1/annuallydo_Linux_x86_64.tar.gz"
      sha256 "29ee0d417cc0ebf7b9a4156d226332036ae0629d29bcf0edb5dce316857682be"

      def install
        bin.install "annuallydo"
      end
    end
  end
end
