# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anynepali < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anynepali"
  version "0.0.0"

  on_macos do
    url "https://github.com/taylormonacelli/anynepali/releases/download/v0.0.0/anynepali_Darwin_x86_64.tar.gz"
    sha256 "988baea98abd4c3c245b691a0a452426b9b0f834812199cfc6502cae69647fdb"

    def install
      bin.install "anynepali"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anynepali
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/anynepali/releases/download/v0.0.0/anynepali_Linux_x86_64.tar.gz"
      sha256 "0a538fb2765e42584945d3af6c6b738f86a7c9cebf566307248d646706cfbc8e"

      def install
        bin.install "anynepali"
      end
    end
  end
end
