# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyonea8l < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anyonea8l"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/anyonea8l/releases/download/v0.0.3/anyonea8l_Darwin_x86_64.tar.gz"
    sha256 "66754e313963f127246b6279da0ffdd70e7e03c0296edbfed77355ab95be7cf5"

    def install
      bin.install "anyonea8l"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anyonea8l
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/anyonea8l/releases/download/v0.0.3/anyonea8l_Linux_x86_64.tar.gz"
        sha256 "14038e1592998d3f6d321790230e834b4036beefdb28e563d6fe40207c969a1d"

        def install
          bin.install "anyonea8l"
        end
      end
    end
  end
end
