# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyoneindonesian < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anyoneindonesian"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/anyoneindonesian/releases/download/v0.0.1/anyoneindonesian_Darwin_x86_64.tar.gz"
    sha256 "c62b9a143bec7bcfb2fe45df5debafed046cb728fe82ad1c20257521d9232483"

    def install
      bin.install "anyoneindonesian"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anyoneindonesian
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/anyoneindonesian/releases/download/v0.0.1/anyoneindonesian_Linux_x86_64.tar.gz"
      sha256 "534d32073c5e2f578fa4fb9eb93d1eb9daa8b51d71d6d6447921d442bf9c0609"

      def install
        bin.install "anyoneindonesian"
      end
    end
  end
end
