# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyonea8l < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anyonea8l"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/anyonea8l/releases/download/v0.0.2/anyonea8l_Darwin_x86_64.tar.gz"
    sha256 "ccc43cfd90f6e15b6021165cd106dc09c5c6a823ce5d5190bb1b68d751775a95"

    def install
      bin.install "anyonea8l"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anyonea8l
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/anyonea8l/releases/download/v0.0.2/anyonea8l_Linux_x86_64.tar.gz"
        sha256 "681d8ea40952cabbe5a7c537989e2f407b37002418dc1407d694587d2427e484"

        def install
          bin.install "anyonea8l"
        end
      end
    end
  end
end
