# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyoneindonesian < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anyoneindonesian"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/anyoneindonesian/releases/download/v0.0.3/anyoneindonesian_Darwin_x86_64.tar.gz"
    sha256 "3164d163c0c7cb932651cf2b8e0a853abc70e22ae85460d59dac725709df44a4"

    def install
      bin.install "anyoneindonesian"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anyoneindonesian
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/anyoneindonesian/releases/download/v0.0.3/anyoneindonesian_Linux_x86_64.tar.gz"
        sha256 "0e8b14a0c2bdb45265bf4e20911206111629d022f78045cde3dc8114c1bdcca5"

        def install
          bin.install "anyoneindonesian"
        end
      end
    end
  end
end
