# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyonenew < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anyonenew"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/anyonenew/releases/download/v0.0.1/anyonenew_Darwin_x86_64.tar.gz"
    sha256 "491b9c49042de9789ebc29ac7a55d228e3655f96ae6a83d9c243393b2829068d"

    def install
      bin.install "anyonenew"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anyonenew
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/anyonenew/releases/download/v0.0.1/anyonenew_Linux_x86_64.tar.gz"
      sha256 "a69d5ed3722806941835319f47785df758c48847ca53a89549a74a62ca2870f3"

      def install
        bin.install "anyonenew"
      end
    end
  end
end
