# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anytown < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/anytown"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/anytown/releases/download/v0.0.2/anytown_Darwin_x86_64.tar.gz"
    sha256 "e40b4efbfecc572e18ea116003ec14213a07dbe6aac93c59179eda4302ddb3e3"

    def install
      bin.install "anytown"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Anytown
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/anytown/releases/download/v0.0.2/anytown_Linux_x86_64.tar.gz"
        sha256 "9e2b730cf50c662298d1c300649c3a407dc9390b496e663961be723e9ebf4e4e"

        def install
          bin.install "anytown"
        end
      end
    end
  end
end
