# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backcan < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/backcan"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/backcan/releases/download/v0.0.1/backcan_Darwin_x86_64.tar.gz"
    sha256 "995fc080b119ff49f3932bfd68d51145a0c89eb3e145dfd640095ed275afb8e1"

    def install
      bin.install "backcan"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Backcan
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/backcan/releases/download/v0.0.1/backcan_Linux_x86_64.tar.gz"
        sha256 "bb6efb6ba194a141cfb9cdfc1de9a011ea3ad4abd5936934ca3e2f528b5781e3"

        def install
          bin.install "backcan"
        end
      end
    end
  end
end
