# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bismarckianton < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/bismarckianton"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/bismarckianton/releases/download/v0.0.8/bismarckianton_Darwin_x86_64.tar.gz"
    sha256 "07b94b82a8fae414651e7dd0a1f9230809ad3e60bbf7b1e74c45a81609714e43"

    def install
      bin.install "bismarckianton"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bismarckianton
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/bismarckianton/releases/download/v0.0.8/bismarckianton_Linux_x86_64.tar.gz"
        sha256 "cb7ed31272b00b28283ca0a49929224d95407c6f843040e6603e84b83a3d5090"

        def install
          bin.install "bismarckianton"
        end
      end
    end
  end
end
