# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bismarckianton < Formula
  desc ""
  homepage "https://github.com/gkwa/bismarckianton"
  version "0.0.3"

  on_macos do
    url "https://github.com/taylormonacelli/bismarckianton/releases/download/v0.0.3/bismarckianton_Darwin_x86_64.tar.gz"
    sha256 "d47a2854cb30ab91d28a8b5db6b679744347eb15a650031cc266cf674ae6fe39"

    def install
      bin.install "bismarckianton"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bismarckianton
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/bismarckianton/releases/download/v0.0.3/bismarckianton_Linux_x86_64.tar.gz"
      sha256 "0561b395a1f70b7182268a34c8cde41ba19f709975f165faae03dc3a89fd22bb"

      def install
        bin.install "bismarckianton"
      end
    end
  end
end
