# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bismarckianton < Formula
  desc ""
  homepage "https://github.com/gkwa/bismarckianton"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/bismarckianton/releases/download/v0.0.1/bismarckianton_Darwin_x86_64.tar.gz"
    sha256 "f96ac47424b4b1e9f72044bc743060ef35e1156fa71c81073432fb1a77559bd9"

    def install
      bin.install "bismarckianton"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bismarckianton
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/bismarckianton/releases/download/v0.0.1/bismarckianton_Linux_x86_64.tar.gz"
      sha256 "052b72025e5742fbc5fc65e3aa1175c03866b4783c7953dd7436d6813fdfe5b6"

      def install
        bin.install "bismarckianton"
      end
    end
  end
end
