# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brassbug < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/brassbug"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/brassbug/releases/download/v0.0.1/brassbug_Darwin_x86_64.tar.gz"
    sha256 "dff30f7b35bc6cc94fb552074031ddf28f86c1d91049f2859b106a57c61d1dca"

    def install
      bin.install "brassbug"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Brassbug
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/brassbug/releases/download/v0.0.1/brassbug_Linux_x86_64.tar.gz"
        sha256 "a9e43fee0d4c4ace6aef5fcee0a3fbdeb2a3cd49505a069a801dda4c8c0b252a"

        def install
          bin.install "brassbug"
        end
      end
    end
  end
end
