# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bravehercules < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/bravehercules"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/bravehercules/releases/download/v0.0.1/bravehercules_Darwin_x86_64.tar.gz"
    sha256 "bd7d620d1d6d45267448a05185037afa3881c16c9c9e5e039c9a5c6b5a011991"

    def install
      bin.install "bravehercules"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Bravehercules
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/bravehercules/releases/download/v0.0.1/bravehercules_Linux_x86_64.tar.gz"
        sha256 "da9cef982de72705dd78b9d730093343f6d62662a37225a00fb43e3906451952"

        def install
          bin.install "bravehercules"
        end
      end
    end
  end
end
