# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brimfulcatamaran < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/brimfulcatamaran"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/brimfulcatamaran/releases/download/v0.0.2/brimfulcatamaran_Darwin_x86_64.tar.gz"
    sha256 "d21436998b176aea7f0d99bcbd5624e4648f6da3832305ed129de3a39a443e93"

    def install
      bin.install "brimfulcatamaran"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Brimfulcatamaran
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/brimfulcatamaran/releases/download/v0.0.2/brimfulcatamaran_Linux_x86_64.tar.gz"
        sha256 "eea9e96ed8d2338f79abf0ae26fde0c351a1e8a41f16b308c29efb935ebb857d"

        def install
          bin.install "brimfulcatamaran"
        end
      end
    end
  end
end
