# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chineseorange < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/chineseorange"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/chineseorange/releases/download/v0.0.2/chineseorange_Darwin_x86_64.tar.gz"
    sha256 "101c35dcf8a5823f869ebae97de49214ff018d8d0e7c38df538aa1e7f3b09cc0"

    def install
      bin.install "chineseorange"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Chineseorange
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/chineseorange/releases/download/v0.0.2/chineseorange_Linux_x86_64.tar.gz"
        sha256 "a48e4f7099e1a8a3801bcfcf9f371a8645b9f78ae402f335f195b601a5efb3a0"

        def install
          bin.install "chineseorange"
        end
      end
    end
  end
end
