# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudelf < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.4"

  on_macos do
    url "https://github.com/taylormonacelli/fogcrow/releases/download/v0.0.4/fogcrow_Darwin_x86_64.tar.gz"
    sha256 "da1a0bf6d5199fd95fd7b1e98801ec7fedc244ce584b6b5b939b9ce20a4aef46"

    def install
      bin.install "fogcrow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudelf
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/fogcrow/releases/download/v0.0.4/fogcrow_Linux_x86_64.tar.gz"
      sha256 "94e457032ec3ef43aa6bad5ef9d8a4aa9ab9afd3c5a11e79eb75f9538d0be393"

      def install
        bin.install "fogcrow"
      end
    end
  end
end
