# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudelf < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.32"

  on_macos do
    url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.32/cloudelf_Darwin_x86_64.tar.gz"
    sha256 "8f390e3bede514205a64791561ce0c8d14b33070fb612efe4c75dc5594c12450"

    def install
      bin.install "cloudelf"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudelf
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.32/cloudelf_Linux_x86_64.tar.gz"
      sha256 "dcfea88e8fbd8560ff48e2b58d0adb8ea6541a488cca286ad890ffd35d31f148"

      def install
        bin.install "cloudelf"
      end
    end
  end
end
