# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudeagle < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.4"

  on_macos do
    url "https://github.com/gkwa/cloudeagle/releases/download/v0.0.4/cloudeagle_Darwin_x86_64.tar.gz"
    sha256 "6330dc22909a453f47ea6a6a9452c322d983e7a1328c292a3ebafbd1d77dc302"

    def install
      bin.install "cloudeagle"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudeagle
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/cloudeagle/releases/download/v0.0.4/cloudeagle_Linux_x86_64.tar.gz"
      sha256 "7b616ac5150972865f00c218b4667171335c42214c27a6beecd2e0d4ae472ac4"

      def install
        bin.install "cloudeagle"
      end
    end
  end
end
