# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudelf < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.29"

  on_macos do
    url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.29/cloudelf_Darwin_x86_64.tar.gz"
    sha256 "591c79d46394bacf373cc1529a121cb5bc5edffacb6876c28fa2fc7c3a19d483"

    def install
      bin.install "cloudelf"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudelf
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/cloudelf/releases/download/v0.0.29/cloudelf_Linux_x86_64.tar.gz"
      sha256 "ffe3701436787eb41fb4bee533d742a49fe71f95ed2a90cde6c3c87e13d56401"

      def install
        bin.install "cloudelf"
      end
    end
  end
end
