# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curiosturkey < Formula
  desc ""
  homepage "https://github.com/gkwa/curiosturkey"
  version "0.0.7"

  on_macos do
    url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.7/curiosturkey_Darwin_x86_64.tar.gz"
    sha256 "49bcc0759fff000ed916b5f19371348d4555e08f003cb1726729f35b6f890921"

    def install
      bin.install "curiosturkey"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Curiosturkey
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.7/curiosturkey_Linux_x86_64.tar.gz"
        sha256 "c5e2cf57826d1334637005e3145733fbfced7023c3f94c30ea336913f39dbefa"

        def install
          bin.install "curiosturkey"
        end
      end
    end
  end
end
