# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curiosturkey < Formula
  desc ""
  homepage "https://github.com/gkwa/curiosturkey"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.3/curiosturkey_Darwin_x86_64.tar.gz"
    sha256 "4687e18e5674d7d1dc5fd3ccd04b992ffb1e15945d908b33446d691133e4c67b"

    def install
      bin.install "curiosturkey"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Curiosturkey
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.3/curiosturkey_Linux_x86_64.tar.gz"
        sha256 "5dcae340c1604948cd26bf07abb8b5610ca6d8915f7f7686ba5cbed944a2fb1f"

        def install
          bin.install "curiosturkey"
        end
      end
    end
  end
end
