# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Curiosturkey < Formula
  desc ""
  homepage "https://github.com/gkwa/curiosturkey"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.6/curiosturkey_Darwin_x86_64.tar.gz"
    sha256 "ce88cc85251b8d27f429706cc6987f9da2e3759c9f5bcb309d3e508c159fc15b"

    def install
      bin.install "curiosturkey"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Curiosturkey
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/curiosturkey/releases/download/v0.0.6/curiosturkey_Linux_x86_64.tar.gz"
        sha256 "d2fd0f647f645c7e887ffd981eb2ba8f22bb6b7959e0d26b117a3c553204cc01"

        def install
          bin.install "curiosturkey"
        end
      end
    end
  end
end
