# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eachit < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/eachit/releases/download/v0.0.3/eachit_Darwin_x86_64.tar.gz"
    sha256 "1f027dd8941ee374fffcea410750ce614729f061737daf46317a2c0eb46f88b3"

    def install
      bin.install "eachit"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Eachit
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/eachit/releases/download/v0.0.3/eachit_Linux_x86_64.tar.gz"
      sha256 "46c9132c763cbe4cc4c73d7303350ca601e2129f9a1ca6ac9bb63ea82908d5ee"

      def install
        bin.install "eachit"
      end
    end
  end
end
