# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Enoughparse < Formula
  desc ""
  homepage "https://github.com/gkwa/enoughparse"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/enoughparse/releases/download/v0.0.1/enoughparse_Darwin_x86_64.tar.gz"
    sha256 "87bea973428e4376fc7d7ebf4e964a882fbbdd0b85bd7378182ff255f6895373"

    def install
      bin.install "enoughparse"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Enoughparse
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/enoughparse/releases/download/v0.0.1/enoughparse_Linux_x86_64.tar.gz"
        sha256 "7f1ab073612d29d02804f587688912d287f8f4948451903f5417cb1424401d49"

        def install
          bin.install "enoughparse"
        end
      end
    end
  end
end
