# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fewport < Formula
  desc ""
  homepage "https://github.com/gkwa/fewport"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/fewport/releases/download/v0.0.3/fewport_Darwin_x86_64.tar.gz"
    sha256 "9ebb8d7b5f3dff0391855d08565fc1aa69ceed5177861b0b897dce23f12a7f20"

    def install
      bin.install "fewport"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fewport
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/fewport/releases/download/v0.0.3/fewport_Linux_x86_64.tar.gz"
        sha256 "88d6415a4beaf0e86b84c33290fe2b765a2d99a8ae0b6b2893b95a1049189bca"

        def install
          bin.install "fewport"
        end
      end
    end
  end
end
