# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fewport < Formula
  desc ""
  homepage "https://github.com/gkwa/fewport"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/fewport/releases/download/v0.0.2/fewport_Darwin_x86_64.tar.gz"
    sha256 "177d2a5acfcf3b689d50a31f344b680415699a64b8c646b440605c16e52c84ae"

    def install
      bin.install "fewport"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fewport
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/fewport/releases/download/v0.0.2/fewport_Linux_x86_64.tar.gz"
        sha256 "a23133f2975c13a3dc7a4802d07c3b80247ae0e789c6118142bf2f9369712928"

        def install
          bin.install "fewport"
        end
      end
    end
  end
end
