# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fewport < Formula
  desc ""
  homepage "https://github.com/gkwa/fewport"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/fewport/releases/download/v0.0.1/fewport_Darwin_x86_64.tar.gz"
    sha256 "a27f04041149da60cf16eb4d29a8d585881c21692ca1a922859d3eecc39e66ee"

    def install
      bin.install "fewport"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fewport
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/fewport/releases/download/v0.0.1/fewport_Linux_x86_64.tar.gz"
        sha256 "d7a963edf54d74ff44ffc427775217761f3ebac3d448b23ece2c75012a60cf01"

        def install
          bin.install "fewport"
        end
      end
    end
  end
end
