# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fogcrow < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.7"

  on_macos do
    url "https://github.com/gkwa/fogcrow/releases/download/v0.0.7/fogcrow_Darwin_x86_64.tar.gz"
    sha256 "87c3bd1de2b86114a556bf7ed05da7e26eefd544086466acfa8c3c96f43b9715"

    def install
      bin.install "fogcrow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fogcrow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/fogcrow/releases/download/v0.0.7/fogcrow_Linux_x86_64.tar.gz"
      sha256 "4b5eca188f3e04fcc0a2dfa18eb2e338e238fc29b3735ab1b87f07cd0c7e6770"

      def install
        bin.install "fogcrow"
      end
    end
  end
end
