# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fogcrow < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.6"

  on_macos do
    url "https://github.com/taylormonacelli/fogcrow/releases/download/v0.0.6/fogcrow_Darwin_x86_64.tar.gz"
    sha256 "3d2e43f4e971f03e597b99e036b10af75d4cd2de2fec31714fcffc56cf530fa4"

    def install
      bin.install "fogcrow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fogcrow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/fogcrow/releases/download/v0.0.6/fogcrow_Linux_x86_64.tar.gz"
      sha256 "801eb86adb2f79bb62b9d70b4494ddbc779ceba76e98b0c8044cae20fceb93e4"

      def install
        bin.install "fogcrow"
      end
    end
  end
end
