# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fragiledonkey < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.9"

  on_macos do
    url "https://github.com/gkwa/fragiledonkey/releases/download/v0.0.9/fragiledonkey_Darwin_x86_64.tar.gz"
    sha256 "826cd7b597bca0349257552dbeea44b77fbfcf6621fd7721195ab33fc789f8d4"

    def install
      bin.install "fragiledonkey"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Fragiledonkey
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/fragiledonkey/releases/download/v0.0.9/fragiledonkey_Linux_x86_64.tar.gz"
        sha256 "2285f51d508741f6cdaa58be207d67a05d6fdcfcfdbdaf0432ce530ca62f66be"

        def install
          bin.install "fragiledonkey"
        end
      end
    end
  end
end
