# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gracefulturnip < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/gracefulturnip"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/gracefulturnip/releases/download/v0.0.2/gracefulturnip_Darwin_x86_64.tar.gz"
    sha256 "3bc6071693e5470c3916b28f2aaf6d286232f7c0b80efbf26af0f35f4e53c6e6"

    def install
      bin.install "gracefulturnip"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Gracefulturnip
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/gracefulturnip/releases/download/v0.0.2/gracefulturnip_Linux_x86_64.tar.gz"
        sha256 "2ff4df1969853adbd93e3eed8d109a60d2337205826f2b03b04a8f6e12911396"

        def install
          bin.install "gracefulturnip"
        end
      end
    end
  end
end
