# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greengossip < Formula
  desc ""
  homepage "https://github.com/gkwa/greengossip"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/greengossip/releases/download/v0.0.3/greengossip_Darwin_x86_64.tar.gz"
    sha256 "025705884c3f01ad52b61adf77dca9fd87deb73bbc8d44f814ddea993116cb00"

    def install
      bin.install "greengossip"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Greengossip
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/greengossip/releases/download/v0.0.3/greengossip_Linux_x86_64.tar.gz"
        sha256 "295fa12cbbf076b6e98fa509818140e806b75450eda820e7efb4a6025af715c7"

        def install
          bin.install "greengossip"
        end
      end
    end
  end
end
