# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greengossip < Formula
  desc ""
  homepage "https://github.com/gkwa/greengossip"
  version "0.0.5"

  on_macos do
    url "https://github.com/gkwa/greengossip/releases/download/v0.0.5/greengossip_Darwin_x86_64.tar.gz"
    sha256 "1cc9ed1e7e51c1fe84d2db46bdc6afff604a7cfeef37d8156c7ea83e24721e9a"

    def install
      bin.install "greengossip"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Greengossip
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/greengossip/releases/download/v0.0.5/greengossip_Linux_x86_64.tar.gz"
        sha256 "3cef6684e4b704491094676bccf7bc12379cc96795799530c9d9c52218261bd2"

        def install
          bin.install "greengossip"
        end
      end
    end
  end
end
