# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Greengossip < Formula
  desc ""
  homepage "https://github.com/gkwa/greengossip"
  version "0.0.4"

  on_macos do
    url "https://github.com/gkwa/greengossip/releases/download/v0.0.4/greengossip_Darwin_x86_64.tar.gz"
    sha256 "e8adafcbffcf8c49eb7108642118fbe00cb3727c940b1bb4f91b25cdb4ee2f63"

    def install
      bin.install "greengossip"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Greengossip
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/greengossip/releases/download/v0.0.4/greengossip_Linux_x86_64.tar.gz"
        sha256 "a03f42037983ec10abd408de892bd62aad409db47a1ba65fb98dd43312203e22"

        def install
          bin.install "greengossip"
        end
      end
    end
  end
end
