# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hercow < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/hercow/releases/download/v0.0.2/hercow_Darwin_x86_64.tar.gz"
    sha256 "76c1610a2d779d95942922607b3447908b4701a8c6fb97853ae99a7292ba149e"

    def install
      bin.install "hercow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Hercow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/hercow/releases/download/v0.0.2/hercow_Linux_x86_64.tar.gz"
      sha256 "cfdb6ef38f11983bd0147051b276460065c16a586d76a1136f6cf2be11a1e01c"

      def install
        bin.install "hercow"
      end
    end
  end
end
