# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hercow < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.14"

  on_macos do
    url "https://github.com/gkwa/hercow/releases/download/v0.0.14/hercow_Darwin_x86_64.tar.gz"
    sha256 "97c04a266dce01ee2059163db3e357aeca6cdde0b75bba3baea835cf2dbc0403"

    def install
      bin.install "hercow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Hercow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/hercow/releases/download/v0.0.14/hercow_Linux_x86_64.tar.gz"
      sha256 "19635b6439688d0ff8d449357f80b7459a50ad0415354c5c38ff02f1e94f1512"

      def install
        bin.install "hercow"
      end
    end
  end
end
