# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hercow < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.11"

  on_macos do
    url "https://github.com/gkwa/hercow/releases/download/v0.0.11/hercow_Darwin_x86_64.tar.gz"
    sha256 "fc2ea669a0a04cb15b8a47e82eb7948956019e8082593cff31e3775c36ab2b9e"

    def install
      bin.install "hercow"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Hercow
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/hercow/releases/download/v0.0.11/hercow_Linux_x86_64.tar.gz"
      sha256 "81bb0a68e730ba21be7869d84a56210c3918b45df2032754f9ba1c53a1832642"

      def install
        bin.install "hercow"
      end
    end
  end
end
