# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howbob < Formula
  desc ""
  homepage "https://github.com/gkwa/howbob"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/howbob/releases/download/v0.0.8/howbob_Darwin_x86_64.tar.gz"
    sha256 "2d5c566e6b3d89f461d2031ffaaebe35f93a5d3b5d2fdbd3075d15b2358a5bbc"

    def install
      bin.install "howbob"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Howbob
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/howbob/releases/download/v0.0.8/howbob_Linux_x86_64.tar.gz"
        sha256 "134b1e8b24d44b91d5d39945ccbbd57095b67add568bd0a8eba789120922191e"

        def install
          bin.install "howbob"
        end
      end
    end
  end
end
