# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howbob < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.5"

  on_macos do
    url "https://github.com/gkwa/howbob/releases/download/v0.0.5/howbob_Darwin_x86_64.tar.gz"
    sha256 "2201166bf31f6b6d07d810c1d9cf8e302e701754c302ae39940cbb19288444fa"

    def install
      bin.install "howbob"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Howbob
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/howbob/releases/download/v0.0.5/howbob_Linux_x86_64.tar.gz"
      sha256 "5ee89093740eefd311b2bb7bd4863dd15bbe21d7a13546cfd268ced303b4097f"

      def install
        bin.install "howbob"
      end
    end
  end
end
