# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Irisqueen < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/irisqueen/releases/download/v0.0.2/irisqueen_Darwin_x86_64.tar.gz"
    sha256 "dff0c94f94f69f11222de3dbf94f4731251b98eb04e501f5603307d839522f3f"

    def install
      bin.install "irisqueen"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Irisqueen
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/irisqueen/releases/download/v0.0.2/irisqueen_Linux_x86_64.tar.gz"
      sha256 "a21267d623cf02b296427a6e0f79d6d7ccf25b29e352ac0ffb806f739c975dea"

      def install
        bin.install "irisqueen"
      end
    end
  end
end
