# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itchyjuly < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/itchyjuly"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/itchyjuly/releases/download/v0.0.1/itchyjuly_Darwin_x86_64.tar.gz"
    sha256 "ed910ef18e979be185379e024fff2e2ea69079b1bb179b2c3d622b46cc71033d"

    def install
      bin.install "itchyjuly"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Itchyjuly
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/itchyjuly/releases/download/v0.0.1/itchyjuly_Linux_x86_64.tar.gz"
      sha256 "308cd8adcf078b2523ad6eaae4b6fda266bba38830113df7100d735d0e9c5122"

      def install
        bin.install "itchyjuly"
      end
    end
  end
end
