# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itmetrics < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.19"

  on_macos do
    url "https://github.com/gkwa/itmetrics/releases/download/v0.0.19/itmetrics_Darwin_x86_64.tar.gz"
    sha256 "4d354b0d2586016de37cfbd838950873ebc9ba95226385a6dad903b607cfceaa"

    def install
      bin.install "itmetrics"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Itmetrics
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/itmetrics/releases/download/v0.0.19/itmetrics_Linux_x86_64.tar.gz"
      sha256 "e97ca7ba53e2af64fe5cd3c1f1cb3be6a29d28cb8f37d9ded06edc918f6df36e"

      def install
        bin.install "itmetrics"
      end
    end
  end
end
