# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Itmetrics < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/itmetrics/releases/download/v0.0.6/itmetrics_Darwin_x86_64.tar.gz"
    sha256 "108f3f34af7429ce569ad3ad53acb35ac84f546930a69bad40f590a4a4857eb7"

    def install
      bin.install "itmetrics"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Itmetrics
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/itmetrics/releases/download/v0.0.6/itmetrics_Linux_x86_64.tar.gz"
      sha256 "a8444bb3a4d4e8f66bff5b35bb64a5da8018bf9c8f2b6a7ea852b9be7e7e28dd"

      def install
        bin.install "itmetrics"
      end
    end
  end
end
