# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lessmay < Formula
  desc ""
  homepage "https://github.com/gkwa/lessmay"
  version "0.0.9"

  on_macos do
    url "https://github.com/gkwa/lessmay/releases/download/v0.0.9/lessmay_Darwin_x86_64.tar.gz"
    sha256 "7f1c99520f5a3478798f67de488d95bcb12060799896b7253310b5d7d0934509"

    def install
      bin.install "lessmay"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lessmay
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/lessmay/releases/download/v0.0.9/lessmay_Linux_x86_64.tar.gz"
        sha256 "26281b2327fcdcd56e715d73ec9f71f59554a6cd3819a8faf682d0276b017694"

        def install
          bin.install "lessmay"
        end
      end
    end
  end
end
