# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lessmay < Formula
  desc ""
  homepage "https://github.com/gkwa/lessmay"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/lessmay/releases/download/v0.0.2/lessmay_Darwin_x86_64.tar.gz"
    sha256 "174126d7168b64cd2ded812f44666b200e4f77cf5bd4470edee0e24b3fa08d3f"

    def install
      bin.install "lessmay"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lessmay
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/lessmay/releases/download/v0.0.2/lessmay_Linux_x86_64.tar.gz"
        sha256 "693230636b0e3a673f7aa4c70a9bf1c6184e8ac1c17da89d8bdba9043fbf1a59"

        def install
          bin.install "lessmay"
        end
      end
    end
  end
end
