# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lessmay < Formula
  desc ""
  homepage "https://github.com/gkwa/lessmay"
  version "0.0.5"

  on_macos do
    url "https://github.com/gkwa/lessmay/releases/download/v0.0.5/lessmay_Darwin_x86_64.tar.gz"
    sha256 "4eda18817a55db64b2b61c9c83c823cf5498e30b783045739a7488b2115870b0"

    def install
      bin.install "lessmay"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Lessmay
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/lessmay/releases/download/v0.0.5/lessmay_Linux_x86_64.tar.gz"
        sha256 "7ff5005afc0dbb8ace60d57134517c72bcdb0ab37baaa16acf6f8377e2bc6c71"

        def install
          bin.install "lessmay"
        end
      end
    end
  end
end
