# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Limejoy < Formula
  desc ""
  homepage "https://github.com/gkwa/limejoy"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/limejoy/releases/download/v0.0.8/limejoy_Darwin_x86_64.tar.gz"
    sha256 "a86c7106c9e1f3758accc2de8b49aa94321749dcb84e42d19c08e9a5f85bf7c0"

    def install
      bin.install "limejoy"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Limejoy
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/limejoy/releases/download/v0.0.8/limejoy_Linux_x86_64.tar.gz"
        sha256 "e7f5f0c087521c968448cba59a24f894d2aeb299d7551a46b7ba94f0181ef602"

        def install
          bin.install "limejoy"
        end
      end
    end
  end
end
