# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Limejoy < Formula
  desc ""
  homepage "https://github.com/gkwa/limejoy"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/limejoy/releases/download/v0.0.3/limejoy_Darwin_x86_64.tar.gz"
    sha256 "6cdb2565a995760b194755131d6557eabccd13b349ddd87f7a648f3144ade063"

    def install
      bin.install "limejoy"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Limejoy
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/limejoy/releases/download/v0.0.3/limejoy_Linux_x86_64.tar.gz"
        sha256 "9a312b1bcc1cbd9d64a78f070139e12821d2e9fbf1fa0288f40a818857c7379b"

        def install
          bin.install "limejoy"
        end
      end
    end
  end
end
