# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Littlewill < Formula
  desc ""
  homepage "https://github.com/gkwa/littlewill"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/littlewill/releases/download/v0.0.1/littlewill_Darwin_x86_64.tar.gz"
    sha256 "e84488ba4cfa98eab7a9dbc4a081b1847af5f609ccfdb9e6192a1029a08ff5d1"

    def install
      bin.install "littlewill"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Littlewill
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/littlewill/releases/download/v0.0.1/littlewill_Linux_x86_64.tar.gz"
        sha256 "fb2c2e82018c20e99baaa742ac1b43cd337dc5bfaf79e528065bd96ec3c9f20d"

        def install
          bin.install "littlewill"
        end
      end
    end
  end
end
