# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Littlewill < Formula
  desc ""
  homepage "https://github.com/gkwa/littlewill"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/littlewill/releases/download/v0.0.3/littlewill_Darwin_x86_64.tar.gz"
    sha256 "a370e3a37e535c748a3a33dbb9d355480ea2610f8e14041ec0d0f4791bc59bb5"

    def install
      bin.install "littlewill"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Littlewill
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/littlewill/releases/download/v0.0.3/littlewill_Linux_x86_64.tar.gz"
        sha256 "ffd1d0a2926b058833025d0960c0a7faebda81f09e3f84d36313fd1082b7708a"

        def install
          bin.install "littlewill"
        end
      end
    end
  end
end
