# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Littlewill < Formula
  desc ""
  homepage "https://github.com/gkwa/littlewill"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/littlewill/releases/download/v0.0.8/littlewill_Darwin_x86_64.tar.gz"
    sha256 "2622d7fc30e551ec4edf18f55d6360ed3ce434410a9538cc0ab41bfa93d65e2c"

    def install
      bin.install "littlewill"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Littlewill
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/littlewill/releases/download/v0.0.8/littlewill_Linux_x86_64.tar.gz"
        sha256 "7bb8ac4a45243dc3669a0f5a39667766d7777105c3d483b7ecd22cf7f7a9702a"

        def install
          bin.install "littlewill"
        end
      end
    end
  end
end
