# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manywest < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/manywest/releases/download/v0.0.1/manywest_Darwin_x86_64.tar.gz"
    sha256 "ae1afe4d1bdee37b08de5ea98ec21344f41bea09ee4be093db8def8d990f3be4"

    def install
      bin.install "manywest"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Manywest
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/manywest/releases/download/v0.0.1/manywest_Linux_x86_64.tar.gz"
      sha256 "4a9f4101a61b1fb9e2f2f1261582273703908d20dc33993354dd0a5cc3d2f05f"

      def install
        bin.install "manywest"
      end
    end
  end
end
