# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manywest < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/manywest/releases/download/v0.0.2/manywest_Darwin_x86_64.tar.gz"
    sha256 "b9a73d69acbf9df9fb5a7bd7015a79ab14f499f41cbb3b3f6ef0690d36a52ab0"

    def install
      bin.install "manywest"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Manywest
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/manywest/releases/download/v0.0.2/manywest_Linux_x86_64.tar.gz"
      sha256 "2b477581d7acbb72767c713080a9a886517ec9c298ae7dd24ef012d23765548d"

      def install
        bin.install "manywest"
      end
    end
  end
end
