# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Manywest < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/manywest/releases/download/v0.0.6/manywest_Darwin_x86_64.tar.gz"
    sha256 "7b5c86da3a792c018c96cec90e4bf3613f3499d12bcf05cc2962e17dece3ba03"

    def install
      bin.install "manywest"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Manywest
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/manywest/releases/download/v0.0.6/manywest_Linux_x86_64.tar.gz"
        sha256 "844184885ba70de52fef5f301811043adcce20bd250f2a1a060ece0598593e36"

        def install
          bin.install "manywest"
        end
      end
    end
  end
end
