# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myaction < Formula
  desc ""
  homepage "https://github.com/gkwa/myaction"
  version "0.0.1"

  on_macos do
    url "https://github.com/gkwa/myaction/releases/download/v0.0.1/myaction_Darwin_x86_64.tar.gz"
    sha256 "6e13ea8873338fc93390ec8dd02fe1fbb349ce84549d70350ab6839125228193"

    def install
      bin.install "myaction"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Myaction
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/myaction/releases/download/v0.0.1/myaction_Linux_x86_64.tar.gz"
        sha256 "e3cbccbe64c5bfcedf5d163c67b52c387d63e9cb926a5c66462b7996cf91f297"

        def install
          bin.install "myaction"
        end
      end
    end
  end
end
