# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myaction < Formula
  desc ""
  homepage "https://github.com/gkwa/myaction"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/myaction/releases/download/v0.0.2/myaction_Darwin_x86_64.tar.gz"
    sha256 "7bd659082b93f8242e8764f9a6461bda14344cd30ab8cab4a50db57658c92691"

    def install
      bin.install "myaction"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Myaction
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/myaction/releases/download/v0.0.2/myaction_Linux_x86_64.tar.gz"
        sha256 "975b7f9171d84885f1ad553febf67da2935920f16e7f3c3ec8a3057f8c84b2b2"

        def install
          bin.install "myaction"
        end
      end
    end
  end
end
