# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysite6 < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/mysite6/releases/download/v0.0.2/mysite6_Darwin_x86_64.tar.gz"
    sha256 "2814d56b16321093522b5adb9f536013cb74acbc34168681643d884a2e51e476"

    def install
      bin.install "mysite6"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mysite6
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/mysite6/releases/download/v0.0.2/mysite6_Linux_x86_64.tar.gz"
      sha256 "fe07d454ee1f20f3b3a3346c60f2263a396a670ed6296ff7ae4e4f083dad0bb8"

      def install
        bin.install "mysite6"
      end
    end
  end
end
