# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysite6 < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/mysite6"
  version "0.0.1"

  on_macos do
    url "https://github.com/taylormonacelli/mysite6/releases/download/v0.0.1/mysite6_Darwin_x86_64.tar.gz"
    sha256 "06447d95ab79e6604a7843489be9addefc25a51359aa89d5acdff0004f1977c0"

    def install
      bin.install "mysite6"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mysite6
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/mysite6/releases/download/v0.0.1/mysite6_Linux_x86_64.tar.gz"
      sha256 "6bc79497ae78919b0decc0c005da2eddfa8422323664dd80fd1301636fbabe0a"

      def install
        bin.install "mysite6"
      end
    end
  end
end
