# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mysite6 < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/mysite6"
  version "0.0.3"

  on_macos do
    url "https://github.com/taylormonacelli/mysite6/releases/download/v0.0.3/mysite6_Darwin_x86_64.tar.gz"
    sha256 "1c5139b836bf94b94b940a60048bb89f4e9744cdc6a7e27b824adb676dc9e07e"

    def install
      bin.install "mysite6"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Mysite6
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/taylormonacelli/mysite6/releases/download/v0.0.3/mysite6_Linux_x86_64.tar.gz"
      sha256 "778dd37042f0c6a74a6e7718d9181abe88b11916973e31012c4632f6619ba252"

      def install
        bin.install "mysite6"
      end
    end
  end
end
