# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myville < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.12"

  on_macos do
    url "https://github.com/gkwa/myville/releases/download/v0.0.12/myville_Darwin_x86_64.tar.gz"
    sha256 "0dda04f3762de1942098464e383c21cc2da271e1cff3d0aabad10020e7d1b915"

    def install
      bin.install "myville"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Myville
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/myville/releases/download/v0.0.12/myville_Linux_x86_64.tar.gz"
        sha256 "ee8b6fe51710890f02216268b509f4b45be30db975c8104f71c3ec2552949822"

        def install
          bin.install "myville"
        end
      end
    end
  end
end
