# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myville < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.14"

  on_macos do
    url "https://github.com/gkwa/myville/releases/download/v0.0.14/myville_Darwin_x86_64.tar.gz"
    sha256 "01f482c2fb2a51a85aa31a5646f9db1a8ce4fe7b61ce298dade53239934eff0b"

    def install
      bin.install "myville"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Myville
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/myville/releases/download/v0.0.14/myville_Linux_x86_64.tar.gz"
        sha256 "0ef36efe8bc8194e2e5776336d343f7be931ea9f203ec6ef43fe1a3756bf45d2"

        def install
          bin.install "myville"
        end
      end
    end
  end
end
