# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myville < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.9"

  on_macos do
    url "https://github.com/gkwa/myville/releases/download/v0.0.9/myville_Darwin_x86_64.tar.gz"
    sha256 "a57b62c5a2301f71f190d4c45008cd79e0e549309de6eea460dd6cd161eec87a"

    def install
      bin.install "myville"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Myville
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/myville/releases/download/v0.0.9/myville_Linux_x86_64.tar.gz"
      sha256 "e63b73ef34d7caf82c604665c708575a87931d4adf2e8b5dcf9a38e755aba718"

      def install
        bin.install "myville"
      end
    end
  end
end
