# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nearwait < Formula
  desc ""
  homepage "https://github.com/gkwa/nearwait"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/nearwait/releases/download/v0.0.8/nearwait_Darwin_x86_64.tar.gz"
    sha256 "c26bf7762dc370042327b5bb289132a4ab28d8e05569808d5398ffde7e55c18b"

    def install
      bin.install "nearwait"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Nearwait
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/nearwait/releases/download/v0.0.8/nearwait_Linux_x86_64.tar.gz"
        sha256 "a2f438beccb3102fc1f22701692d90bbe683c88a69e8db15abfa9493df928171"

        def install
          bin.install "nearwait"
        end
      end
    end
  end
end
