# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nearwait < Formula
  desc ""
  homepage "https://github.com/gkwa/nearwait"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/nearwait/releases/download/v0.0.3/nearwait_Darwin_x86_64.tar.gz"
    sha256 "bd2720d377685109a839bc63b3c0ac43080b461e9bf36b4efcf41bb3ab98b308"

    def install
      bin.install "nearwait"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Nearwait
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/nearwait/releases/download/v0.0.3/nearwait_Linux_x86_64.tar.gz"
        sha256 "8cb94cc9c2845aa565df90d8f4bf6efaabd384e770f49728c1ebfd1d34757daa"

        def install
          bin.install "nearwait"
        end
      end
    end
  end
end
