# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nearwait < Formula
  desc ""
  homepage "https://github.com/gkwa/nearwait"
  version "0.1.2"

  on_macos do
    url "https://github.com/gkwa/nearwait/releases/download/v0.1.2/nearwait_Darwin_x86_64.tar.gz"
    sha256 "8293432c9ec3b517839240a9e8f2835bcfe08453585318ef913acdd36b9fcd3f"

    def install
      bin.install "nearwait"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Nearwait
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/nearwait/releases/download/v0.1.2/nearwait_Linux_x86_64.tar.gz"
        sha256 "27116dd125f4f4a2dc9d679ba6c08e10817ff9513423ba562e5c40304a045d1a"

        def install
          bin.install "nearwait"
        end
      end
    end
  end
end
