# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouravocado < Formula
  desc ""
  homepage "https://github.com/gkwa/ouravocado"
  version "0.0.5"

  on_macos do
    url "https://github.com/gkwa/ouravocado/releases/download/v0.0.5/ouravocado_Darwin_x86_64.tar.gz"
    sha256 "1eb6a209ed24fceb2b97daa8c7ff55297529a95edc7bfa4da89cc96a8becffe2"

    def install
      bin.install "ouravocado"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ouravocado
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/ouravocado/releases/download/v0.0.5/ouravocado_Linux_x86_64.tar.gz"
        sha256 "989f13b0283bba308a860ae71ca43a833cd8f6fcc830a5a0182b9f581036f42d"

        def install
          bin.install "ouravocado"
        end
      end
    end
  end
end
