# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ouravocado < Formula
  desc ""
  homepage "https://github.com/gkwa/ouravocado"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/ouravocado/releases/download/v0.0.6/ouravocado_Darwin_x86_64.tar.gz"
    sha256 "fd69483454e3b94c39a4f4d7b56fc78212392a0a70b47af60be2bec3671c19cd"

    def install
      bin.install "ouravocado"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ouravocado
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/ouravocado/releases/download/v0.0.6/ouravocado_Linux_x86_64.tar.gz"
        sha256 "de9f6852e96ab2246f4113113f697d84452d5b52fe2143b798fcf9be2c67af5d"

        def install
          bin.install "ouravocado"
        end
      end
    end
  end
end
