# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ourlock < Formula
  desc ""
  homepage "https://github.com/gkwa/ourlock"
  version "0.0.3"

  on_macos do
    url "https://github.com/gkwa/ourlock/releases/download/v0.0.3/ourlock_Darwin_x86_64.tar.gz"
    sha256 "5777cd74f12d913b5638b69dd8995a70d96383c3c4e504c70da9f39c178ff55f"

    def install
      bin.install "ourlock"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ourlock
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/ourlock/releases/download/v0.0.3/ourlock_Linux_x86_64.tar.gz"
        sha256 "d76f4494dd7dd60b114cd344e8df2e70254f8a8c4566c08a970c0df5538a2d0f"

        def install
          bin.install "ourlock"
        end
      end
    end
  end
end
