# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ourlock < Formula
  desc ""
  homepage "https://github.com/gkwa/ourlock"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/ourlock/releases/download/v0.0.2/ourlock_Darwin_x86_64.tar.gz"
    sha256 "e9c3477869696690f2b6323e6e87411d94baa369350337e33d4ab00d67f93caf"

    def install
      bin.install "ourlock"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ourlock
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/ourlock/releases/download/v0.0.2/ourlock_Linux_x86_64.tar.gz"
        sha256 "78f1211ebec3dc2952571085773bb1f0160b7fa20e09fadf89210dcb124f679b"

        def install
          bin.install "ourlock"
        end
      end
    end
  end
end
