# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Polarpaw < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/homebrew-tools"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/polarpaw/releases/download/v0.0.2/polarpaw_Darwin_x86_64.tar.gz"
    sha256 "1c21220b2956d7e4e6b3e8307e8524d4152a205556cbc3c434960e5bc5e1be50"

    def install
      bin.install "polarpaw"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Polarpaw
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/gkwa/polarpaw/releases/download/v0.0.2/polarpaw_Linux_x86_64.tar.gz"
      sha256 "86b6e5179b749bae75341f4d1c9441c05c85359254fc7630dc31480b328ab26f"

      def install
        bin.install "polarpaw"
      end
    end
  end
end
