# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Underbeing < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/underbeing"
  version "0.0.6"

  on_macos do
    url "https://github.com/gkwa/underbeing/releases/download/v0.0.6/underbeing_Darwin_x86_64.tar.gz"
    sha256 "3ec807e69be847d7f5eeea4baf2546807d149b85e274fbc0faeeefeb370b1747"

    def install
      bin.install "underbeing"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Underbeing
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/underbeing/releases/download/v0.0.6/underbeing_Linux_x86_64.tar.gz"
        sha256 "0fe2e5813e6bec3fd9ac5afefffb8ea30b9a6485a1dade57d67ffa37d421caf7"

        def install
          bin.install "underbeing"
        end
      end
    end
  end
end
