# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Underbeing < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/underbeing"
  version "0.0.8"

  on_macos do
    url "https://github.com/gkwa/underbeing/releases/download/v0.0.8/underbeing_Darwin_x86_64.tar.gz"
    sha256 "6d5311dd6441816a050ae580468a1c97a6a0ca9c5faa9fbc1ae2e25fb63be84f"

    def install
      bin.install "underbeing"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Underbeing
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/underbeing/releases/download/v0.0.8/underbeing_Linux_x86_64.tar.gz"
        sha256 "012e7bb9049f16ee7e07db008aa8f66fb518f890dd6411267b5c2d525c0462a5"

        def install
          bin.install "underbeing"
        end
      end
    end
  end
end
