# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Underbeing < Formula
  desc ""
  homepage "https://github.com/taylormonacelli/underbeing"
  version "0.0.7"

  on_macos do
    url "https://github.com/gkwa/underbeing/releases/download/v0.0.7/underbeing_Darwin_x86_64.tar.gz"
    sha256 "28fb9330386e1df0c8cb59f58426c579e7606f1081b51226d63bcae087b6aa3a"

    def install
      bin.install "underbeing"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Underbeing
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/underbeing/releases/download/v0.0.7/underbeing_Linux_x86_64.tar.gz"
        sha256 "8591fa2fd78d3debad0669e58b13878811275988e3b5eb82084cf5cde9d86fc0"

        def install
          bin.install "underbeing"
        end
      end
    end
  end
end
