# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wholeoverride < Formula
  desc ""
  homepage "https://github.com/gkwa/wholeoverride"
  version "0.0.2"

  on_macos do
    url "https://github.com/gkwa/wholeoverride/releases/download/v0.0.2/wholeoverride_Darwin_x86_64.tar.gz"
    sha256 "229714e6dc3fbe8ad6065cac33d1dc48fb7580503dd170bb1f05122833e4fc6a"

    def install
      bin.install "wholeoverride"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Wholeoverride
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gkwa/wholeoverride/releases/download/v0.0.2/wholeoverride_Linux_x86_64.tar.gz"
        sha256 "e415e0442abcc6c13a4f726b87363a20d2df4cd74b80a9e52ba3178d02857959"

        def install
          bin.install "wholeoverride"
        end
      end
    end
  end
end
